- name: Install Apache latest version
  yum:
    name: httpd
    state: latest

- name: Replace httpd.conf config file
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf

- name: Copy {{ vhost }} configuration file
  template: src={{ vhost }}.conf dest=/etc/httpd/conf.d/{{ vhost }}.conf

- name: Sure apache starts at boot
  systemd:
    name: httpd
    enabled: yes
  notify:
    - Restart Apache

- name: Start apache by systemd
  systemd:
    name: httpd
    state: started

- name: Allow port 443 in firewalld
  firewalld:
    zone: public
    port: 443/tcp
    permanent: yes
    state: enabled

- name: Allow port 80 in firewalld
  firewalld:
      zone: public
      port: 80/tcp
      permanent: yes
      state: enabled
  notify:
    - Reload firewalld
  

