- name: Change hostname Osticket
  shell: |
    hostnamectl set-hostname {{hostname}}

- name: pull code from Github
  git:
    repo: https://github.com/osTicket/osTicket.git
    dest: /var/www/{{ osticket }}
    clone: yes
    update: yes
    force: yes


- name: Replace ost config file
  template:
    src: ost-config.php
    dest: "/var/www/{{ osticket }}/include/"


- name: Change DocumentRoot Permission
  file:
    path: "{{ document_root }}/{{ osticket }}"
    owner: apache
    group: apache
    mode: 0755
    recurse: yes


- name: Move file osticket to /var/www/html/
  shell: |
    mv /var/www/osticket/ /var/www/html/

- name: Change DocumentRoot Permission
  file:
    path: "{{ document_root }}/html"
    owner: apache
    group: apache
    mode: 0755
    recurse: yes


- name: send a message to chat in playbook
  telegram:
    token: '1792774787:AAEYZ5OocqsWHWuIBizx5RSxrVTdH8m089A'
    chat_id: -547842145
    msg: Ansible task (Osticket) finished