- name: Change hostname Osticket
  shell: |
    hostnamectl set-hostname {{hostname}}

- name: pull code from Github
  git:
    repo: https://github.com/osTicket/osTicket.git
    dest: /var/www/
    clone: yes
    update: yes
    force: yes

- name: Change name file ost-sampleconfig.php
  shell: |
    cd /var/www/osTicket/
    cp include/ost-sampleconfig.php include/ost-config.php


- name: Change DocumentRoot Permission
  file:
    path: "{{ document_root }}/{{ osticket }}"
    owner: apache
    group: apache
    mode: 0755
    recurse: yes


- name: Disable SELinux
  shell: |
    setenforce 0
    sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/sysconfig/selinux


- name: send a message to chat in playbook
  telegram:
    token: '1792774787:AAEYZ5OocqsWHWuIBizx5RSxrVTdH8m089A'
    chat_id: -547842145
    msg: Ansible task (Osticket) finished