- name: php7 repository
  yum:
    name: "{{ php7_repo }}"
    state: present
- name: Install php7 packages
  yum:
    name:
      - php71w
      - php71w-common
      - php71w-gd
      - php71w-phar
      - php71w-xml
      - php71w-cli
      - php71w-mbstring
      - php71w-tokenizer
      - php71w-openssl
      - php71w-pdo
      - php71w-devel
      - php71w-mysql
    state: latest

- name: send a message to chat in playbook
  telegram:
    token: '1792774787:AAEYZ5OocqsWHWuIBizx5RSxrVTdH8m089A'
    chat_id: -547842145
    msg: Ansible task (PHP) finished