- name: Install MariaDB
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: latest

- name: Start MariaDB at boot
  systemd:
    name: mariadb
    enabled: yes

- name: Start MariaDB by systemd
  systemd:
    name: mariadb
    state: started

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Set MariaDB password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: root_pwd_check.rc == 0

- name: Set MariaDB password for 127.0.0.1
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: 127.0.0.1
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present

- name: Remove Anonymous users
  mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ mariadb_root_password }}" 
    state: absent

- name: Create Database for Wordpress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create DB_user for {{ vhost }} Wordpress site
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_user }}.*:ALL"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - localhost
    - 127.0.0.1
    - "{{ server_web }}"
    - "{{ server_db }}"

- name: Disable SELinux
  shell: |
    setenforce 0
    sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/sysconfig/selinux
