---
- name: setting config sysctl
  hosts: all
  become: yes
  become_user: root

  vars:
    - hostname: docker

  tasks:
    - name: Stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False
    
    
    - name: update hostnames
      hostname:
        name: "{{ hostname }}"  


    - name: upgrade all packages
      yum: name=* state=latest


    - name: Add repositories Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes


    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes


    - name: install package
      yum:
        name:      
          - wget
          - nano
          - epel-release
          - yum-utils
          - docker-ce
        state: latest


    - name: Start Docker 
      service:
        name: docker
        state: started
        enabled: True